-- To add support for your custom firearms, copy this file
-- and match the types your mod is using to the appropriate model

CoavinsFirearms.Include('Base.Pistol',             'GenericPistol')
CoavinsFirearms.Include('Base.Pistol2',            'GenericPistol')
CoavinsFirearms.Include('Base.Pistol3',            'GenericPistol')
CoavinsFirearms.Include('Base.Glock17',            'GenericPistol')
CoavinsFirearms.Include('Base.ColtAce',            'GenericPistol')
CoavinsFirearms.Include('Base.Revolver',           'GenericRevolver')
CoavinsFirearms.Include('Base.Revolver_Long',      'GenericRevolver')
CoavinsFirearms.Include('Base.Revolver_Short',     'GenericRevolver')
CoavinsFirearms.Include('Base.ColtPython',         'GenericRevolver')
CoavinsFirearms.Include('Base.ColtPythonHunter',   'GenericRevolver')
CoavinsFirearms.Include('Base.ColtAnaconda',       'GenericRevolver')
CoavinsFirearms.Include('Base.ColtPeacemaker',     'GenericRevolver')
CoavinsFirearms.Include('Base.ColtSingleAction22', 'GenericRevolver')
CoavinsFirearms.Include('Base.DoubleBarrelShotgun',        'GenericShotgun')
CoavinsFirearms.Include('Base.DoubleBarrelShotgunSawnoff', 'GenericShotgun')
CoavinsFirearms.Include('Base.Shotgun',                    'GenericShotgun')
CoavinsFirearms.Include('Base.ShotgunSawnoff',             'GenericShotgun')
CoavinsFirearms.Include('Base.Mossberg500',                'GenericShotgun')
CoavinsFirearms.Include('Base.Mossberg500Tactical',        'GenericShotgun')
CoavinsFirearms.Include('Base.Remington870Wood',           'GenericShotgun')
CoavinsFirearms.Include('Base.Remington870Sawnoff',        'GenericShotgun')
CoavinsFirearms.Include('Base.M37',                        'GenericShotgun')
CoavinsFirearms.Include('Base.M37Sawnoff',                 'GenericShotgun')
CoavinsFirearms.Include('Base.SPAS12',                     'GenericShotgun')
CoavinsFirearms.Include('Base.LAW12',                      'GenericShotgun')
CoavinsFirearms.Include('Base.AssaultRifle', 'M16Rifle')
CoavinsFirearms.Include('Base.M16A2',        'M16Rifle')
CoavinsFirearms.Include('Base.M733',         'M16Rifle')
CoavinsFirearms.Include('Base.AR15',         'M16Rifle')
--CoavinsFirearms.Include('Base.FN_FAL', '')
--CoavinsFirearms.Include('Base.M60', '')
--CoavinsFirearms.Include('Base.AK47', '')
