-- To add support for your custom firearms, copy this file
-- and match the types your mod is using to the appropriate model

CoavinsFirearms.Include('Base.Pistol',             'GenericPistol')
CoavinsFirearms.Include('Base.Pistol2',            'GenericPistol')
CoavinsFirearms.Include('Base.Pistol3',            'GenericPistol')
CoavinsFirearms.Include('Base.DEagle_Long',        'GenericPistol')
CoavinsFirearms.Include('Base.Judge_45LC',         'GenericRevolver')
CoavinsFirearms.Include('Base.Judge_410g',         'GenericRevolver')
CoavinsFirearms.Include('Base.Judge513_45LC',      'GenericRevolver')
CoavinsFirearms.Include('Base.Judge513_410g',      'GenericRevolver')
CoavinsFirearms.Include('Base.Judge513_Long_45LC', 'GenericRevolver')
CoavinsFirearms.Include('Base.Judge513_Long_410g', 'GenericRevolver')
CoavinsFirearms.Include('Base.TXS_804_45LC',       'GenericRevolver')
CoavinsFirearms.Include('Base.TXS_804_410g',       'GenericRevolver')
CoavinsFirearms.Include('Base.Colt1855',           'GenericRevolver')
CoavinsFirearms.Include('Base.SW_M500',            'GenericRevolver')
CoavinsFirearms.Include('Base.Revolver_Short_357', 'GenericRevolver')
CoavinsFirearms.Include('Base.Revolver_Short',     'GenericRevolver')
CoavinsFirearms.Include('Base.Revolver_357',       'GenericRevolver')
CoavinsFirearms.Include('Base.Revolver_Long',      'GenericRevolver')
CoavinsFirearms.Include('Base.Revolver_Long_357',  'GenericRevolver')
CoavinsFirearms.Include('Base.VIPER_G2',           'GenericShotgun')
CoavinsFirearms.Include('Base.Moss500_20',         'GenericShotgun')
CoavinsFirearms.Include('Base.10855_Silver',       'GenericShotgun')
CoavinsFirearms.Include('Base.HuntingRifle',       'BoltActionRifle')
CoavinsFirearms.Include('Base.VarmintRifle',       'BoltActionRifle')
CoavinsFirearms.Include('Base.AssaultRifle',       'M16Rifle')
CoavinsFirearms.Include('Base.AssaultRifle2',      'M16Rifle')
