-- To add support for your custom firearms, copy this file
-- and match the types your mod is using to the appropriate model

-- Guns of 93

-- Pistols
CoavinsFirearms.Include('Base.M9','GenericPistol')
CoavinsFirearms.Include('Base.Beretta92FS','GenericPistol')
CoavinsFirearms.Include('Base.Officer1911','GenericPistol')
CoavinsFirearms.Include('Base.DeltaElite','GenericPistol')
CoavinsFirearms.Include('Base.DeltaEliteRail','GenericPistol')
CoavinsFirearms.Include('Base.Javelina','GenericPistol')
CoavinsFirearms.Include('Base.JavelinaRail','GenericPistol')
CoavinsFirearms.Include('Base.DE44','GenericPistol')
CoavinsFirearms.Include('Base.BHP','GenericPistol')
CoavinsFirearms.Include('Base.Glock17','GenericPistol')
CoavinsFirearms.Include('Base.Glock22','GenericPistol')
CoavinsFirearms.Include('Base.Glock20','GenericPistol')
CoavinsFirearms.Include('Base.SW5906','GenericPistol')
CoavinsFirearms.Include('Base.SW4006','GenericPistol')
CoavinsFirearms.Include('Base.RugP89','GenericPistol')
CoavinsFirearms.Include('Base.RugP90','GenericPistol')
CoavinsFirearms.Include('Base.P226','GenericPistol')
CoavinsFirearms.Include('Base.P228','GenericPistol')
CoavinsFirearms.Include('Base.P7M8','GenericPistol')
CoavinsFirearms.Include('Base.P7M13','GenericPistol')
CoavinsFirearms.Include('Base.USP9','GenericPistol')
CoavinsFirearms.Include('Base.USP40','GenericPistol')
CoavinsFirearms.Include('Base.CZ75B','GenericPistol')
CoavinsFirearms.Include('Base.Raven25','GenericPistol')
CoavinsFirearms.Include('Base.J22','GenericPistol')
CoavinsFirearms.Include('Base.P380','GenericPistol')
CoavinsFirearms.Include('Base.83Cheetah','GenericPistol')
CoavinsFirearms.Include('Base.Hammerless','GenericPistol')
CoavinsFirearms.Include('Base.PPK','GenericPistol')
CoavinsFirearms.Include('Base.Bobcat','GenericPistol')
CoavinsFirearms.Include('Base.Buckmark','GenericPistol')
CoavinsFirearms.Include('Base.Rugmark','GenericPistol')
CoavinsFirearms.Include('Base.TEC9','GenericPistol')
CoavinsFirearms.Include('Base.Uzi','GenericPistol')
CoavinsFirearms.Include('Base.MAC10','GenericPistol')
CoavinsFirearms.Include('Base.Uzi','GenericPistol')
CoavinsFirearms.Include('Base.CalicoPistol','GenericPistol')

-- Revolvers
CoavinsFirearms.Include('Base.SW625','GenericRevolver')
CoavinsFirearms.Include('Base.SW625Rail','GenericRevolver')
CoavinsFirearms.Include('Base.SW29','GenericRevolver')
CoavinsFirearms.Include('Base.SW29Rail','GenericRevolver')
CoavinsFirearms.Include('Base.SW36','GenericRevolver')
CoavinsFirearms.Include('Base.SW10','GenericRevolver')
CoavinsFirearms.Include('Base.SW65','GenericRevolver')
CoavinsFirearms.Include('Base.SW586','GenericRevolver')
CoavinsFirearms.Include('Base.SW586Rail','GenericRevolver')
CoavinsFirearms.Include('Base.SW17','GenericRevolver')
CoavinsFirearms.Include('Base.SW17Rail','GenericRevolver')
CoavinsFirearms.Include('Base.GP100','GenericRevolver')
CoavinsFirearms.Include('Base.GP100Rail','GenericRevolver')
CoavinsFirearms.Include('Base.GP101','GenericRevolver')
CoavinsFirearms.Include('Base.SecuritySix','GenericRevolver')
CoavinsFirearms.Include('Base.SecuritySixRail','GenericRevolver')
CoavinsFirearms.Include('Base.Python','GenericRevolver')
CoavinsFirearms.Include('Base.PythonRail','GenericRevolver')
CoavinsFirearms.Include('Base.Anaconda','GenericRevolver')
CoavinsFirearms.Include('Base.AnacondaRail','GenericRevolver')
CoavinsFirearms.Include('Base.ColtDet','GenericRevolver')
CoavinsFirearms.Include('Base.ColtArmy','GenericRevolver')

-- Manual rifles
CoavinsFirearms.Include('Base.R308Rem700','BoltActionRifle')
CoavinsFirearms.Include('Base.R3006Rem700','BoltActionRifle')
CoavinsFirearms.Include('Base.R223Rem788','BoltActionRifle')
CoavinsFirearms.Include('Base.R223Rem700','BoltActionRifle')
CoavinsFirearms.Include('Base.R308Rem788','BoltActionRifle')
CoavinsFirearms.Include('Base.M24','BoltActionRifle')
CoavinsFirearms.Include('Base.W308WinM70','BoltActionRifle')
CoavinsFirearms.Include('Base.W3006WinM70','BoltActionRifle')
CoavinsFirearms.Include('Base.W223WinM70','BoltActionRifle')
CoavinsFirearms.Include('Base.Win69','BoltActionRifle')
CoavinsFirearms.Include('Base.R308RugM77','BoltActionRifle')
CoavinsFirearms.Include('Base.R3006RugM77','BoltActionRifle')
CoavinsFirearms.Include('Base.R223RugM77','BoltActionRifle')
CoavinsFirearms.Include('Base.M1903','BoltActionRifle')
CoavinsFirearms.Include('Base.M1917','BoltActionRifle')
CoavinsFirearms.Include('Base.Mauser98K','BoltActionRifle')

-- Automatic rifles
CoavinsFirearms.Include('Base.M16A2', 'M16Rifle')
CoavinsFirearms.Include('Base.M14308', 'M16Rifle')
CoavinsFirearms.Include('Base.M1A', 'M16Rifle')
CoavinsFirearms.Include('Base.AR15', 'M16Rifle')
CoavinsFirearms.Include('Base.M16A2Rail', 'M16Rifle')
CoavinsFirearms.Include('Base.CAR15', 'M16Rifle')
CoavinsFirearms.Include('Base.CAR15Rail', 'M16Rifle')
--CoavinsFirearms.Include('Base.M723', 'M16Rifle')
--CoavinsFirearms.Include('Base.M723Rail', 'M16Rifle')
--CoavinsFirearms.Include('Base.M733', 'M16Rifle')
--CoavinsFirearms.Include('Base.M733Rail', 'M16Rifle')
--CoavinsFirearms.Include('Base.M635', 'M16Rifle')
--CoavinsFirearms.Include('Base.M635Rail', 'M16Rifle')
--CoavinsFirearms.Include('Base.M249', 'M16Rifle')
--CoavinsFirearms.Include('Base.M249Mag', 'M16Rifle')
--CoavinsFirearms.Include('Base.M60', 'M16Rifle')
CoavinsFirearms.Include('Base.M14Rail', 'M16Rifle')
CoavinsFirearms.Include('Base.M1ARail', 'M16Rifle')
CoavinsFirearms.Include('Base.AR15Rail', 'M16Rifle')
CoavinsFirearms.Include('Base.M1Garand', 'BoltActionRifle')
CoavinsFirearms.Include('Base.M1Carbine', 'BoltActionRifle')
CoavinsFirearms.Include('Base.SKS', 'SKS')
--CoavinsFirearms.Include('Base.Mini14', 'M16Rifle')
--CoavinsFirearms.Include('Base.Mini14Rail', 'M16Rifle')
--CoavinsFirearms.Include('Base.Mini30', 'M16Rifle')
--CoavinsFirearms.Include('Base.Mini30Rail', 'M16Rifle')
--CoavinsFirearms.Include('Base.AKM', 'M16Rifle')
--CoavinsFirearms.Include('Base.AKMS', 'M16Rifle')
--CoavinsFirearms.Include('Base.AKMSFold', 'M16Rifle')
--CoavinsFirearms.Include('Base.T56', 'M16Rifle')
--CoavinsFirearms.Include('Base.AR180', 'M16Rifle')
--CoavinsFirearms.Include('Base.AR180Fold', 'M16Rifle')
--CoavinsFirearms.Include('Base.HK91', 'M16Rifle')
--CoavinsFirearms.Include('Base.FAL', 'M16Rifle')
--CoavinsFirearms.Include('Base.Marlin45', 'M16Rifle')
--CoavinsFirearms.Include('Base.Marlin9', 'M16Rifle')
--CoavinsFirearms.Include('Base.MP5', 'M16Rifle')
--CoavinsFirearms.Include('Base.CalicoRifle', 'M16Rifle')
--CoavinsFirearms.Include('Base.CalicoRifleFold', 'M16Rifle')
--CoavinsFirearms.Include('Base.Rug1022', 'M16Rifle')
--CoavinsFirearms.Include('Base.Marlin60', 'M16Rifle')
--CoavinsFirearms.Include('Base.Brown3006BAR', 'M16Rifle')
--CoavinsFirearms.Include('Base.Brown308BAR', 'M16Rifle')
--CoavinsFirearms.Include('Base.Win30067400', 'M16Rifle')
--CoavinsFirearms.Include('Base.Win3087400', 'M16Rifle')
--CoavinsFirearms.Include('Base.Win61', 'M16Rifle')
--CoavinsFirearms.Include('Base.Rem3006760', 'M16Rifle')
--CoavinsFirearms.Include('Base.Rem308760', 'M16Rifle')
--CoavinsFirearms.Include('Base.Rem223760', 'M16Rifle')
--CoavinsFirearms.Include('Base.SORem870', 'M16Rifle')
--CoavinsFirearms.Include('Base.SOMoss500', 'M16Rifle')
--CoavinsFirearms.Include('Base.Moss590', 'M16Rifle')
--CoavinsFirearms.Include('Base.M590', 'M16Rifle')
--CoavinsFirearms.Include('Base.Win1912', 'M16Rifle')
--CoavinsFirearms.Include('Base.SOWin1912', 'M16Rifle')
--CoavinsFirearms.Include('Base.Win1200', 'M16Rifle')
--CoavinsFirearms.Include('Base.SOWin1200', 'M16Rifle')
--CoavinsFirearms.Include('Base.Win1200Def', 'M16Rifle')
--CoavinsFirearms.Include('Base.SOIthaca37', 'M16Rifle')
--CoavinsFirearms.Include('Base.Ithaca37Riot', 'M16Rifle')
--CoavinsFirearms.Include('Base.Win1400', 'M16Rifle')
--CoavinsFirearms.Include('Base.SOWin1400', 'M16Rifle')
--CoavinsFirearms.Include('Base.Rem1100', 'M16Rifle')
--CoavinsFirearms.Include('Base.SORem1100', 'M16Rifle')
--CoavinsFirearms.Include('Base.BenelliM3', 'M16Rifle')
