-- To add support for your custom firearms, copy this file
-- and match the types your mod is using to the appropriate model

-- Guns of 93

-- ************
-- Guns93Guns.txt
-- ************

-- Pistols
CoavinsFirearms.Include('Base.M9','GenericPistol')
CoavinsFirearms.Include('Base.Beretta92FS','GenericPistol')
CoavinsFirearms.Include('Base.M1911A1','GenericPistol')
CoavinsFirearms.Include('Base.M1911A1Rail','GenericPistol')
CoavinsFirearms.Include('Base.Gov1911','GenericPistol')
CoavinsFirearms.Include('Base.Gov1911Rail','GenericPistol')
CoavinsFirearms.Include('Base.Longslide','GenericPistol')
CoavinsFirearms.Include('Base.LongslideRail','GenericPistol')
CoavinsFirearms.Include('Base.Command1911','GenericPistol')
CoavinsFirearms.Include('Base.Officer1911','GenericPistol')
CoavinsFirearms.Include('Base.DeltaElite','GenericPistol')
CoavinsFirearms.Include('Base.DeltaEliteRail','GenericPistol')
CoavinsFirearms.Include('Base.Javelina','GenericPistol')
CoavinsFirearms.Include('Base.JavelinaRail','GenericPistol')
CoavinsFirearms.Include('Base.DE44','GenericPistol')
CoavinsFirearms.Include('Base.BHP','GenericPistol')
CoavinsFirearms.Include('Base.Glock17','GenericPistol')
CoavinsFirearms.Include('Base.Glock22','GenericPistol')
CoavinsFirearms.Include('Base.Glock21','GenericPistol')
CoavinsFirearms.Include('Base.Glock20','GenericPistol')
CoavinsFirearms.Include('Base.SW5906','GenericPistol')
CoavinsFirearms.Include('Base.SW4506','GenericPistol')
CoavinsFirearms.Include('Base.SW4006','GenericPistol')
CoavinsFirearms.Include('Base.RugP89','GenericPistol')
CoavinsFirearms.Include('Base.RugP90','GenericPistol')
CoavinsFirearms.Include('Base.P226','GenericPistol')
CoavinsFirearms.Include('Base.P228','GenericPistol')
CoavinsFirearms.Include('Base.P7M8','GenericPistol')
CoavinsFirearms.Include('Base.P7M13','GenericPistol')
CoavinsFirearms.Include('Base.USP9','GenericPistol')
CoavinsFirearms.Include('Base.USP40','GenericPistol')
CoavinsFirearms.Include('Base.CZ75B','GenericPistol')
CoavinsFirearms.Include('Base.Raven25','GenericPistol')
CoavinsFirearms.Include('Base.J22','GenericPistol')
CoavinsFirearms.Include('Base.P380','GenericPistol')
CoavinsFirearms.Include('Base.83Cheetah','GenericPistol')
CoavinsFirearms.Include('Base.Hammerless','GenericPistol')
CoavinsFirearms.Include('Base.PPK','GenericPistol')
CoavinsFirearms.Include('Base.Bobcat','GenericPistol')
CoavinsFirearms.Include('Base.Buckmark','GenericPistol')
CoavinsFirearms.Include('Base.Rugmark','GenericPistol')
CoavinsFirearms.Include('Base.TEC9','GenericPistol')
CoavinsFirearms.Include('Base.Uzi','GenericPistol')
CoavinsFirearms.Include('Base.MAC10','GenericPistol')
CoavinsFirearms.Include('Base.Uzi','GenericPistol')
CoavinsFirearms.Include('Base.CalicoPistol','GenericPistol')

-- Revolvers
CoavinsFirearms.Include('Base.SW625','GenericRevolver')
CoavinsFirearms.Include('Base.SW625Rail','GenericRevolver')
CoavinsFirearms.Include('Base.SW29','GenericRevolver')
CoavinsFirearms.Include('Base.SW29Rail','GenericRevolver')
CoavinsFirearms.Include('Base.SW36','GenericRevolver')
CoavinsFirearms.Include('Base.SW10','GenericRevolver')
CoavinsFirearms.Include('Base.SW65','GenericRevolver')
CoavinsFirearms.Include('Base.SW586','GenericRevolver')
CoavinsFirearms.Include('Base.SW586Rail','GenericRevolver')
CoavinsFirearms.Include('Base.SW17','GenericRevolver')
CoavinsFirearms.Include('Base.SW17Rail','GenericRevolver')
CoavinsFirearms.Include('Base.GP100','GenericRevolver')
CoavinsFirearms.Include('Base.GP100Rail','GenericRevolver')
CoavinsFirearms.Include('Base.GP101','GenericRevolver')
CoavinsFirearms.Include('Base.SecuritySix','GenericRevolver')
CoavinsFirearms.Include('Base.SecuritySixRail','GenericRevolver')
CoavinsFirearms.Include('Base.Python','GenericRevolver')
CoavinsFirearms.Include('Base.PythonRail','GenericRevolver')
CoavinsFirearms.Include('Base.Anaconda','GenericRevolver')
CoavinsFirearms.Include('Base.AnacondaRail','GenericRevolver')
CoavinsFirearms.Include('Base.ColtDet','GenericRevolver')
CoavinsFirearms.Include('Base.ColtArmy','GenericRevolver')

-- Manual rifles
CoavinsFirearms.Include('Base.R308Rem700','BoltActionRifle')
CoavinsFirearms.Include('Base.R3006Rem700','BoltActionRifle')
CoavinsFirearms.Include('Base.R223Rem788','BoltActionRifle')
CoavinsFirearms.Include('Base.R223Rem700','BoltActionRifle')
CoavinsFirearms.Include('Base.R308Rem788','BoltActionRifle')
CoavinsFirearms.Include('Base.M24','BoltActionRifle')
CoavinsFirearms.Include('Base.W308WinM70','BoltActionRifle')
CoavinsFirearms.Include('Base.W3006WinM70','BoltActionRifle')
CoavinsFirearms.Include('Base.W223WinM70','BoltActionRifle')
CoavinsFirearms.Include('Base.Win69','BoltActionRifle')
CoavinsFirearms.Include('Base.R308RugM77','BoltActionRifle')
CoavinsFirearms.Include('Base.R3006RugM77','BoltActionRifle')
CoavinsFirearms.Include('Base.R223RugM77','BoltActionRifle')
CoavinsFirearms.Include('Base.M1903','BoltActionRifle')
CoavinsFirearms.Include('Base.M1917','BoltActionRifle')
CoavinsFirearms.Include('Base.Mauser98K','BoltActionRifle')

-- Automatic rifles
CoavinsFirearms.Include('Base.M16A2', 'M16Rifle')
CoavinsFirearms.Include('Base.M14308', 'M16Rifle')
CoavinsFirearms.Include('Base.M1A', 'M16Rifle')
CoavinsFirearms.Include('Base.AR15', 'M16Rifle')
CoavinsFirearms.Include('Base.M16A2Rail', 'M16Rifle')
CoavinsFirearms.Include('Base.CAR15', 'M16Rifle')
CoavinsFirearms.Include('Base.CAR15Rail', 'M16Rifle')
--CoavinsFirearms.Include('Base.M723', 'M16Rifle')
--CoavinsFirearms.Include('Base.M723Rail', 'M16Rifle')
--CoavinsFirearms.Include('Base.M733', 'M16Rifle')
--CoavinsFirearms.Include('Base.M733Rail', 'M16Rifle')
--CoavinsFirearms.Include('Base.M635', 'M16Rifle')
--CoavinsFirearms.Include('Base.M635Rail', 'M16Rifle')
--CoavinsFirearms.Include('Base.M249', 'M16Rifle')
--CoavinsFirearms.Include('Base.M249Mag', 'M16Rifle')
--CoavinsFirearms.Include('Base.M60', 'M16Rifle')
CoavinsFirearms.Include('Base.M14Rail', 'M16Rifle')
CoavinsFirearms.Include('Base.M1ARail', 'M16Rifle')
CoavinsFirearms.Include('Base.AR15Rail', 'M16Rifle')
CoavinsFirearms.Include('Base.M1Garand', 'BoltActionRifle')
CoavinsFirearms.Include('Base.M1Carbine', 'BoltActionRifle')
CoavinsFirearms.Include('Base.SKS', 'SKS')
--CoavinsFirearms.Include('Base.Mini14', 'M16Rifle')
--CoavinsFirearms.Include('Base.Mini14Rail', 'M16Rifle')
--CoavinsFirearms.Include('Base.Mini30', 'M16Rifle')
--CoavinsFirearms.Include('Base.Mini30Rail', 'M16Rifle')
--CoavinsFirearms.Include('Base.AKM', 'M16Rifle')
--CoavinsFirearms.Include('Base.AKMS', 'M16Rifle')
--CoavinsFirearms.Include('Base.AKMSFold', 'M16Rifle')
--CoavinsFirearms.Include('Base.T56', 'M16Rifle')
--CoavinsFirearms.Include('Base.AR180', 'M16Rifle')
--CoavinsFirearms.Include('Base.AR180Fold', 'M16Rifle')
--CoavinsFirearms.Include('Base.HK91', 'M16Rifle')
--CoavinsFirearms.Include('Base.FAL', 'M16Rifle')
--CoavinsFirearms.Include('Base.Marlin45', 'M16Rifle')
--CoavinsFirearms.Include('Base.Marlin9', 'M16Rifle')
--CoavinsFirearms.Include('Base.MP5', 'M16Rifle')
--CoavinsFirearms.Include('Base.CalicoRifle', 'M16Rifle')
--CoavinsFirearms.Include('Base.CalicoRifleFold', 'M16Rifle')
--CoavinsFirearms.Include('Base.Rug1022', 'M16Rifle')
--CoavinsFirearms.Include('Base.Marlin60', 'M16Rifle')
--CoavinsFirearms.Include('Base.Marlin3363030', 'M16Rifle')
--CoavinsFirearms.Include('Base.Marlin33644', 'M16Rifle')
--CoavinsFirearms.Include('Base.Marlin39A', 'M16Rifle')
--CoavinsFirearms.Include('Base.Win943030', 'M16Rifle')
--CoavinsFirearms.Include('Base.Win94357', 'M16Rifle')
--CoavinsFirearms.Include('Base.Win9445', 'M16Rifle')
--CoavinsFirearms.Include('Base.Brown3006BAR', 'M16Rifle')
--CoavinsFirearms.Include('Base.Brown308BAR', 'M16Rifle')
--CoavinsFirearms.Include('Base.Win30067400', 'M16Rifle')
--CoavinsFirearms.Include('Base.Win3087400', 'M16Rifle')
--CoavinsFirearms.Include('Base.Win61', 'M16Rifle')
--CoavinsFirearms.Include('Base.Rem3006760', 'GenericShotgun')
--CoavinsFirearms.Include('Base.Rem308760', 'GenericShotgun')
--CoavinsFirearms.Include('Base.Rem223760', 'GenericShotgun')

-- Manual shotguns

CoavinsFirearms.Include('Base.Rem870', 'GenericShotgun')
CoavinsFirearms.Include('Base.Rem870P', 'GenericShotgun')
CoavinsFirearms.Include('Base.SORem870', 'GenericShotgun')
CoavinsFirearms.Include('Base.M870', 'GenericShotgun')
CoavinsFirearms.Include('Base.Moss500', 'GenericShotgun')
CoavinsFirearms.Include('Base.SOMoss500', 'GenericShotgun')
CoavinsFirearms.Include('Base.Moss590', 'GenericShotgun')
CoavinsFirearms.Include('Base.M590', 'GenericShotgun')
CoavinsFirearms.Include('Base.Win1912', 'GenericShotgun')
CoavinsFirearms.Include('Base.SOWin1912', 'GenericShotgun')
CoavinsFirearms.Include('Base.Win1200', 'GenericShotgun')
CoavinsFirearms.Include('Base.SOWin1200', 'GenericShotgun')
CoavinsFirearms.Include('Base.Win1200Def', 'GenericShotgun')
CoavinsFirearms.Include('Base.Ithaca37', 'GenericShotgun')
CoavinsFirearms.Include('Base.SOIthaca37', 'GenericShotgun')
CoavinsFirearms.Include('Base.Ithaca37Riot', 'GenericShotgun')
CoavinsFirearms.Include('Base.StoegerUplander', 'GenericShotgun')
CoavinsFirearms.Include('Base.SOStoegerUplander', 'GenericShotgun')
CoavinsFirearms.Include('Base.SavageFox', 'GenericShotgun')
CoavinsFirearms.Include('Base.SOSavageFox', 'GenericShotgun')
CoavinsFirearms.Include('Base.BrownCitori', 'GenericShotgun')
CoavinsFirearms.Include('Base.SOBrownCitori', 'GenericShotgun')
CoavinsFirearms.Include('Base.Beretta682', 'GenericShotgun')
CoavinsFirearms.Include('Base.SOBeretta682', 'GenericShotgun')
CoavinsFirearms.Include('Base.Win37', 'GenericShotgun')
CoavinsFirearms.Include('Base.SOWin37', 'GenericShotgun')

-- Auto shotguns

CoavinsFirearms.Include('Base.Auto5', 'GenericShotgun')
CoavinsFirearms.Include('Base.SOAuto5', 'GenericShotgun')
CoavinsFirearms.Include('Base.Win1400', 'GenericShotgun')
CoavinsFirearms.Include('Base.SOWin1400', 'GenericShotgun')
CoavinsFirearms.Include('Base.Rem1100', 'GenericShotgun')
CoavinsFirearms.Include('Base.SORem1100', 'GenericShotgun')
CoavinsFirearms.Include('Base.BenelliM3', 'GenericShotgun')
CoavinsFirearms.Include('Base.L395K', 'GenericShotgun')
CoavinsFirearms.Include('Base.SOL395K', 'GenericShotgun')

-- ************
-- Guns93AltCalGuns.txt
-- ************

-- SW 625
CoavinsFirearms.Include('Base.SW625Clip','GenericRevolver')
CoavinsFirearms.Include('Base.SW625ClipRail','GenericRevolver')

-- .357/.38
CoavinsFirearms.Include('Base.SW65Spc','GenericRevolver')
CoavinsFirearms.Include('Base.SW586Spc','GenericRevolver')
CoavinsFirearms.Include('Base.SW586SpcRail','GenericRevolver')
CoavinsFirearms.Include('Base.GP100Spc','GenericRevolver')
CoavinsFirearms.Include('Base.GP100SpcRail','GenericRevolver')
CoavinsFirearms.Include('Base.GP101Spc','GenericRevolver')
CoavinsFirearms.Include('Base.SecuritySixSpc','GenericRevolver')
CoavinsFirearms.Include('Base.SecuritySixSpcRail','GenericRevolver')
CoavinsFirearms.Include('Base.PythonSpc','GenericRevolver')
CoavinsFirearms.Include('Base.PythonSpcRail','GenericRevolver')
CoavinsFirearms.Include('Base.Win94357Spc','GenericRevolver')

-- Buckshot/Slug
CoavinsFirearms.Include('Base.Rem870Slug','GenericRevolver')
CoavinsFirearms.Include('Base.Rem870PSlug','GenericRevolver')
CoavinsFirearms.Include('Base.SORem870Slug','GenericShotgun')
CoavinsFirearms.Include('Base.M870Slug','GenericShotgun')
CoavinsFirearms.Include('Base.Moss500Slug','GenericShotgun')
CoavinsFirearms.Include('Base.SOMoss500Slug','GenericShotgun')
CoavinsFirearms.Include('Base.Moss590Slug','GenericShotgun')
CoavinsFirearms.Include('Base.M590Slug','GenericShotgun')
CoavinsFirearms.Include('Base.Win1912Slug','GenericShotgun')
CoavinsFirearms.Include('Base.SOWin1912Slug','GenericShotgun')
CoavinsFirearms.Include('Base.Win1200Slug','GenericShotgun')
CoavinsFirearms.Include('Base.SOWin1200Slug','GenericShotgun')
CoavinsFirearms.Include('Base.Win1200DefSlug','GenericShotgun')
CoavinsFirearms.Include('Base.Ithaca37Slug','GenericShotgun')
CoavinsFirearms.Include('Base.SOIthaca37Slug','GenericShotgun')
CoavinsFirearms.Include('Base.Ithaca37RiotSlug','GenericShotgun')
CoavinsFirearms.Include('Base.StoegerUplanderSlug','GenericShotgun')
CoavinsFirearms.Include('Base.SOStoegerUplanderSlug','GenericShotgun')
CoavinsFirearms.Include('Base.SavageFoxSlug','GenericShotgun')
CoavinsFirearms.Include('Base.SOSavageFoxSlug','GenericShotgun')
CoavinsFirearms.Include('Base.BrownCitoriSlug','GenericShotgun')
CoavinsFirearms.Include('Base.SOBrownCitoriSlug','GenericShotgun')
CoavinsFirearms.Include('Base.Beretta682Slug','GenericShotgun')
CoavinsFirearms.Include('Base.SOBeretta682Slug','GenericShotgun')
CoavinsFirearms.Include('Base.Auto5Slug','GenericShotgun')
CoavinsFirearms.Include('Base.SOAuto5Slug','GenericShotgun')
CoavinsFirearms.Include('Base.Win1400Slug','GenericShotgun')
CoavinsFirearms.Include('Base.SOWin1400Slug','GenericShotgun')
CoavinsFirearms.Include('Base.Rem1100Slug','GenericShotgun')
CoavinsFirearms.Include('Base.SORem1100Slug','GenericShotgun')
CoavinsFirearms.Include('Base.BenelliM3Slug','GenericShotgun')
