-- To add support for your custom firearms, copy this file
-- and match the types your mod is using to the appropriate model

-- AK_CUSTOM.txt
CoavinsFirearms.Include('Base.AKM_Custom',        'AK47')
CoavinsFirearms.Include('Base.AKM_Custom_Melee',  'AK47')
CoavinsFirearms.Include('Base.AK74_Custom',       'AK47')
CoavinsFirearms.Include('Base.AK74_Custom_Melee', 'AK47')

-- AR_VARIANT.txt
CoavinsFirearms.Include('Base.LVOA_C',                 'Rifle_556')
CoavinsFirearms.Include('Base.LVOA_C_Melee',           'Rifle_556')
CoavinsFirearms.Include('Base.LVOA_C_Melee',           'Rifle_556')
CoavinsFirearms.Include('Base.LVOA_C_INC',             'Rifle_556')
CoavinsFirearms.Include('Base.ADAR',                   'Rifle_556')
CoavinsFirearms.Include('Base.ADAR_Melee',             'Rifle_556')
CoavinsFirearms.Include('Base.MK47',                   'Rifle_556')
CoavinsFirearms.Include('Base.AAC_Honey',              'Rifle_556')
CoavinsFirearms.Include('Base.AAC_Honey_Fold',         'Rifle_556')
CoavinsFirearms.Include('Base.AAC_HoneySD',            'Rifle_556')
CoavinsFirearms.Include('Base.AAC_HoneySD_Fold',       'Rifle_556')
CoavinsFirearms.Include('Base.Bush_AR15_MOE',          'Rifle_556')
CoavinsFirearms.Include('Base.Bush_AR15_MOE_Melee',    'Rifle_556')
CoavinsFirearms.Include('Base.Bush_AR15_MOE_HE',       'Rifle_556')
CoavinsFirearms.Include('Base.Bush_AR15_MOE_INC',      'Rifle_556')
CoavinsFirearms.Include('Base.Bush_XM15',              'Rifle_556')
CoavinsFirearms.Include('Base.Bush_XM15_Melee',        'Rifle_556')
CoavinsFirearms.Include('Base.Bush_XM15_HE',           'Rifle_556')
CoavinsFirearms.Include('Base.Bush_XM15_INC',          'Rifle_556')
CoavinsFirearms.Include('Base.Bush_XM15_Custom',       'Rifle_556')
CoavinsFirearms.Include('Base.Bush_XM15_Custom_Melee', 'Rifle_556')
CoavinsFirearms.Include('Base.Bush_XM15_Custom_HE',    'Rifle_556')
CoavinsFirearms.Include('Base.Bush_XM15_Custom_INC',   'Rifle_556')
CoavinsFirearms.Include('Base.TR1_UltraLight',         'Rifle_556')

-- SIG_MCX.txt
CoavinsFirearms.Include('Base.MCX_Spear','Rifle_556')
CoavinsFirearms.Include('Base.MCX_Spear_Melee','Rifle_556')
CoavinsFirearms.Include('Base.MCX_Spear_HE','Rifle_556')
CoavinsFirearms.Include('Base.MCX_Spear_INC','Rifle_556')
CoavinsFirearms.Include('Base.MCX_Virtus','Rifle_556')
CoavinsFirearms.Include('Base.MCX_Virtus_Melee','Rifle_556')
CoavinsFirearms.Include('Base.MCX_Virtus_HE','Rifle_556')
CoavinsFirearms.Include('Base.MCX_Virtus_INC','Rifle_556')
CoavinsFirearms.Include('Base.MCX_VirtusPatrol','Rifle_556')
CoavinsFirearms.Include('Base.MCX_VirtusPatrol_Melee','Rifle_556')
CoavinsFirearms.Include('Base.MCX_VirtusPatrol_HE','Rifle_556')
CoavinsFirearms.Include('Base.MCX_VirtusPatrol_INC','Rifle_556')
CoavinsFirearms.Include('Base.MCX_Socom','Rifle_556')
CoavinsFirearms.Include('Base.MCX_Socom_Melee','Rifle_556')
CoavinsFirearms.Include('Base.MCX_Socom_HE','Rifle_556')
CoavinsFirearms.Include('Base.MCX_Socom_INC','Rifle_556')
CoavinsFirearms.Include('Base.JW3_TTI_MPX','Rifle_556')
