-- To add support for your custom firearms, copy this file
-- and match the types your mod is using to the appropriate model

CoavinsFirearms:Include('Base.Pistol',             'Pistol')
CoavinsFirearms:Include('Base.Pistol2',            'Pistol')
CoavinsFirearms:Include('Base.Pistol3',            'Pistol')
CoavinsFirearms:Include('Base.Glock17',            'Pistol')
CoavinsFirearms:Include('Base.ColtAce',            'Pistol')
CoavinsFirearms:Include('Base.Revolver',           'Revolver')
CoavinsFirearms:Include('Base.Revolver_Long',      'Revolver')
CoavinsFirearms:Include('Base.Revolver_Short',     'Revolver')
CoavinsFirearms:Include('Base.ColtPython',         'Revolver')
CoavinsFirearms:Include('Base.ColtPythonHunter',   'Revolver')
CoavinsFirearms:Include('Base.ColtAnaconda',       'Revolver')
CoavinsFirearms:Include('Base.ColtPeacemaker',     'Revolver')
CoavinsFirearms:Include('Base.ColtSingleAction22', 'Revolver')
CoavinsFirearms:Include('Base.DoubleBarrelShotgun',        'Shotgun')
CoavinsFirearms:Include('Base.DoubleBarrelShotgunSawnoff', 'Shotgun')
CoavinsFirearms:Include('Base.Shotgun',                    'Shotgun')
CoavinsFirearms:Include('Base.ShotgunSawnoff',             'Shotgun')
CoavinsFirearms:Include('Base.Mossberg500',                'Shotgun')
CoavinsFirearms:Include('Base.Mossberg500Tactical',        'Shotgun')
CoavinsFirearms:Include('Base.Remington870Wood',           'Shotgun')
CoavinsFirearms:Include('Base.Remington870Sawnoff',        'Shotgun')
CoavinsFirearms:Include('Base.M37',                        'Shotgun')
CoavinsFirearms:Include('Base.M37Sawnoff',                 'Shotgun')
CoavinsFirearms:Include('Base.SPAS12',                     'Shotgun')
CoavinsFirearms:Include('Base.LAW12',                      'Shotgun')
